Repository onlinkers/event-discovery-prototype, pull requests merged in 2020-02, with the labels that each got.

#7 Global variables working
  src/App.vue
  src/assets/icons/arrow-left.svg
  src/assets/icons/like-button.svg
  src/assets/icons/mobile-explore-bar/archive.svg
  src/assets/icons/mobile-explore-bar/bulb-outline.png
  src/assets/icons/mobile-explore-bar/earth-outline.png
  src/assets/icons/mobile-explore-bar/globe.svg
  src/assets/icons/mobile-explore-bar/home-outline.png
  src/assets/icons/mobile-explore-bar/home.svg
  src/assets/icons/mobile-explore-bar/person-circle-outline.png
  src/assets/icons/mobile-explore-bar/person.svg
  src/assets/icons/share.svg
  src/assets/sample-img.png
  src/assets/scss/variables.scss
  src/components/exploreBar.vue
  src/global.scss
  src/main.js
  src/router.js
  src/views/EventPage.vue
  src/views/Welcome.vue
  vue.config.js
Labels: documentation, front-end, new feature

#18 Event Ideation Process
  src/assets/icons/arrow-left-dark.svg
  src/assets/icons/arrow-left-light.svg
  src/assets/icons/event-initiation/album-icon.svg
  src/assets/icons/event-initiation/attach-file.svg
  src/assets/icons/event-initiation/bonfire-icon.svg
  src/assets/icons/event-initiation/chat-icon.svg
  src/assets/icons/event-initiation/hourglass-icon.svg
  src/assets/icons/event-initiation/location-icon.svg
  src/assets/icons/share-dark.svg
  src/assets/icons/share-light.svg
  src/assets/scss/mixins.scss
  src/assets/scss/overwrites.scss
  src/assets/scss/variables.css
  src/assets/scss/variables.scss
  src/assets/vectors/chill-vector.svg
  src/assets/vectors/date-vector.svg
  src/assets/vectors/location-vector.svg
  src/assets/vectors/media-vector.svg
  src/assets/vectors/ticket-vector.svg
  src/components/createEventModal.vue
  src/components/exploreBar.vue
  src/components/navButtons.vue
  src/global.scss
  src/main.js
  src/plugins/vuetify.js
  src/router.js
  src/views/EventInitiation.vue
  src/views/EventPage.vue
  src/views/New.vue
  vue.config.js
Labels: URGENT, bug, new feature

#23 Page Responsiveness
  src/components/exploreBar.vue
  src/components/searchBar.vue
  src/global.scss
  src/utils/_utils/formValidation.js
  src/utils/index.js
  src/views/Discover.vue
  src/views/New.vue
  src/views/SignUp.vue
  src/views/Welcome.vue
Labels: URGENT, design, enhancement

#26 Config (ESLint, Pre-commit, README)
  .env.default
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  src/App.vue
  src/components/eventInitiation.vue
  src/components/exploreBar.vue
  src/components/navButtons.vue
  src/components/searchBar.vue
  src/views/Discover.vue
  src/views/EventInitiation.vue
  src/views/EventPage.vue
  src/views/SignUp.vue
  src/views/Welcome.vue
Labels: documentation, enhancement, scalability
