Repository onlinkers/event-discovery-prototype, pull requests merged in 2020-03, with the labels that each got.

#39 Mixins
  src/assets/icons/mobile-explore-bar/explore-eclipse.vue
  src/assets/scss/mixins.scss
  src/components/exploreBar.vue
  src/components/map/Mapbox.vue
  src/components/map/marker.vue
  src/components/navButtons.vue
  src/views/EventInitiation.vue
Labels: front-end, new feature

#40 added prettier configuration to lint to avoid conflict
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/js/eventData.js
  src/router.js
  src/views/EventInitiation.vue
  src/views/EventPage.vue
Labels: enhancement

#49 Event Details Page
  .eslintrc.js
  package-lock.json
  package.json
  src/App.vue
  src/assets/icons/event-page/hourglass.svg
  src/assets/icons/event-page/location.svg
  src/assets/icons/event-page/people.svg
  src/assets/icons/event-page/weather.svg
  src/assets/js/eventData.js
  src/assets/js/mapbox/style.json
  src/assets/scss/mixins.scss
  src/assets/scss/mixins/_alignment-mixins.scss
  src/assets/scss/mixins/_media-mixins.scss
  src/assets/scss/mixins/_typography-mixins.scss
  src/assets/scss/variables.css
  src/assets/scss/variables.scss
  src/components/exploreBar.vue
  src/components/map/Mapbox.vue
  src/components/map/marker.vue
  src/components/navButtons.vue
  src/main.js
  src/router.js
  src/views/Discover.vue
  src/views/EventPage.vue
Labels: enhancement, front-end, new feature

#60 Update dependencies
  package-lock.json
Labels: URGENT
